[package]
name = "cached_result"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
parking_lot = "0.12.0"
tokio = { version = "1.17.0", features = ["macros", "sync", "rt-multi-thread"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
